version: '3'
# https://github.com/puppetlabs/puppet-in-docker-examples/tree/master/compose

services:
  puppet:
    container_name: puppet
    hostname: $PUPPETSERVER_HOSTNAME
    build:
      context: .
      args:
        - PUPPETSERVER_VERSION=$PUPPETSERVER_VERSION
    image: puppetserver:$PUPPETSERVER_VERSION
    restart: unless-stopped
    ports:
      - "8140:8140"
    volumes:
      - ./data/puppet/keys:/etc/puppetlabs/puppet/keys
      - ./data/puppet/ssl:/etc/puppetlabs/puppet/ssl
      - ./data/puppet/r10k:/etc/puppetlabs/r10k
      - ./data/puppet/ssh:/root/.ssh
      - ./data/puppet/environments:/etc/puppetlabs/code/environments
    links:
      - puppetdb:puppetdb
    environment:
      - PUPPETSERVER_HOSTNAME=$PUPPETSERVER_HOSTNAME
      - AUTOSIGN=$PUPPETSERVER_AUTOSIGN


  puppetdb:
    hostname: puppetdb
    container_name: puppetdb
    image: puppet/puppetdb:$PUPPETDB_VERSION
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - ./data/puppetdb/jetty.ini:/etc/puppetlabs/puppetdb/conf.d/jetty.ini
      - ./data/puppetdb/ssl:/etc/puppetlabs/puppetdb/ssl
    environment:
      - PUPPETDB_PASSWORD=$POSTGRES_PASSWORD

  puppetdbpostgres:
    container_name: postgres
    hostname: postgres
    image: puppet/puppetdb-postgres:$PUPPETDBPOSTGRES_VERSION
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=puppetdb
      - POSTGRES_DATABASE=puppetdb
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  # Clone puppetboard repo and build it first
  # https://github.com/voxpupuli/puppetboard
  puppetboard:
    container_name: puppetboard
    hostname: puppetboard
    image: puppetboard
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./data/puppetdb/ssl:/etc/puppetlabs/puppetdb/ssl:ro
    environment:
      - PUPPETDB_HOST=puppetdb
      - PUPPETDB_PORT=8081
      - PUPPETDB_SSL_VERIFY=/etc/puppetlabs/puppetdb/ssl/ca.pem
      - PUPPETDB_KEY=/etc/puppetlabs/puppetdb/ssl/private.pem
      - PUPPETDB_CERT=/etc/puppetlabs/puppetdb/ssl/public.pem
      - INVENTORY_FACTS='Hostname,fqdn, IP Address,ipaddress'
      - ENABLE_CATALOG=True
      - GRAPH_FACTS='architecture,puppetversion,osfamily'
