version: '3'
# https://github.com/puppetlabs/puppet-in-docker-examples/tree/master/compose

services:
  puppet:
    container_name: puppet
    hostname: $PUPPETSERVER_HOSTNAME
    build:
      context: .
      args:
        - PUPPETSERVER_VERSION=$PUPPETSERVER_VERSION
    image: puppetserver:$PUPPETSERVER_VERSION
    restart: unless-stopped
    ports:
      - "8140:8140"
    volumes:
      - ./data/puppet/keys:/etc/puppetlabs/puppet/keys
      - ./data/puppet/ssl:/etc/puppetlabs/puppet/ssl
      - ./data/puppet/r10k:/etc/puppetlabs/r10k
      - ./data/puppet/ssh:/root/.ssh
      - ./data/puppet/environments:/etc/puppetlabs/code/environments
    environment:
      - PUPPETSERVER_HOSTNAME=$PUPPETSERVER_HOSTNAME
      - AUTOSIGN=$PUPPETSERVER_AUTOSIGN
      - CA_ALLOW_SUBJECT_ALT_NAMES=${CA_ALLOW_SUBJECT_ALT_NAMES:-true}

  puppetdbpostgres:
    container_name: postgres
    hostname: postgres
    image: puppet/puppetdb-postgres:$PUPPETDBPOSTGRES_VERSION
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=${POSTGRES_USER:-puppetdb}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-puppetdb}
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  puppetdb:
    hostname: puppetdb
    container_name: puppetdb
    image: puppet/puppetdb:$PUPPETDB_VERSION
    restart: unless-stopped
    volumes:
      - ./data/puppetdb/ssl:/etc/puppetlabs/puppetdb/ssl
      - ./data/puppetdb/jetty.ini:/etc/puppetlabs/puppetdb/conf.d/jetty.ini
    environment:
      - PUPPETDB_PASSWORD=$POSTGRES_PASSWORD
      - PUPPETDB_USER=${POSTGRES_USER:-puppetdb}
      - PUPPETDB_POSTGRES_DATABASE=${POSTGRES_DATABASE:-puppetdb}
      - PUPPETDB_NODE_TTL=${PUPPETDB_NODE_TTL:-1d}
      - PUPPETDB_NODE_PURGE_TTL=${PUPPETDB_NODE_PURGE_TTL:-365d}
      - PUPPETSERVER_HOSTNAME=puppet
      - CERTNAME=$PUPPETDB_CERTNAME
      - SSLDIR=/etc/puppetlabs/puppetdb/ssl
    depends_on:
      - puppetdbpostgres


  # Clone puppetboard repo and build it first
  # https://github.com/voxpupuli/puppetboard
  puppetboard:
    container_name: puppetboard
    hostname: puppetboard
    image: puppetboard
    restart: unless-stopped
    depends_on:
      - puppetdb
    ports:
      - "80:80"
    volumes:
      - ./data/puppetdb/ssl:/etc/puppetlabs/puppetdb/ssl:ro
    environment:
      - PUPPETDB_HOST=puppetdb
      - PUPPETDB_PORT=8081
      - PUPPETDB_SSL_VERIFY=/etc/puppetlabs/puppetdb/ssl/certs/ca.pem
      - PUPPETDB_KEY=/etc/puppetlabs/puppetdb/ssl/private_keys/private.pem
      - PUPPETDB_CERT=/etc/puppetlabs/puppetdb/ssl/certs/public.pem
      - INVENTORY_FACTS='Hostname,fqdn, IP Address,ipaddress'
      - ENABLE_CATALOG=True
      - GRAPH_FACTS='architecture,puppetversion,osfamily'
